### ISSUE TITLE
IPZ VPD parser is failing

### ISSUE THREAD

**Issue by branupama** [ibm-openbmc/openpower-vpd-parser#218]
vpd-parser application is failing to parse IPZ VPD, failed for VTOC ECC check. 

Error:
./build/vpd-parser -f test/ipz_80051.dat 
FileName: ../src/vpd_parser_main.cpp, Line: 52, Func: int main(int, char**), VPD file path recievedtest/ipz_80051.dat
IPZ parser selected for VPD file path test/ipz_80051.dat
FileName: ../src/ipz_parser.cpp, Line: 595, Func: virtual vpd::types::VPDMapVariant vpd::IpzVpdParser::parse(), ERROR: VTOC ECC check Failed
FileName: ../src/vpd_parser_main.cpp, Line: 90, Func: int main(int, char**), std::exception

Findings:
1. "vtocEccCheck()" api is bool type, when this function returns
     true - ecc check is passed
     false - ecc check is failed
     who is calling this function, should have "!vtocEccCheck()" to throw errors when ecc check is failing .
2. we are advancing pointer twice in vtocEccCheck() with Offset::VTOC_PTR. 
       we shouldn't advance pointer with "Offset::VTOC_PTR" to read vtocLength value, instead we should only advance with sizeof(types::RecordOffset).
       
 3. "recordName" is read wrongly in readPT() api, need to fix this as well .
 
 4. readKeywords() api is appending keyword:value to kwdValueMap twice, it should be only once.
   and if there is any keyword which is not present in "supportedKeywords" map, we should have log saying - this keyword type is not supported.

**Comment by RekhaAparna01** [comment]
Fix  -- https://github.com/ibm-openbmc/openpower-vpd-parser/pull/225
