### ISSUE TITLE
Update devTree and device-tree mismatch

### ISSUE THREAD

**Issue by branupama** [ibm-openbmc/openpower-vpd-parser#245]
'devTree' in config JSON and 'device-tree'  in code is being used.
Update it to use either on of it. 
and update worker.cpp to correct  how we are accessing 'devTree' from m_parsedJson["devTree"].value("path", "") .

_Exception got while running vpd-manager:_
FileName: /usr/src/debug/openpower-fru-vpd/1.0+git-r1/src/worker.cpp, Line: 147, Func: void vpd::worker::performInitialSetup(), [json.exception.type_error.306] cannot use value() with string
FileName: /usr/src/debug/openpower-fru-vpd/1.0+git-r1/src/manager.cpp, Line: 82, Func: vpd::manager::Manager(const std::shared_ptr<boost::asio::io_context>&, const std::shared_ptr<sdbusplus::asio::dbus_interface>&, const std::shared_ptr<sdbusplus::asio::connection>&), VPD-Manager service failed. [json.exception.type_error.306] cannot use value() with string
[json.exception.type_error.306] cannot use value() with string

**Comment by RekhaAparna01** [comment]
Done 
PR: https://github.com/ibm-openbmc/openpower-vpd-parser/pull/253
