### ISSUE TITLE
cplusplus.NewDeleteLeaks  : Potential leak of memory warning

### ISSUE THREAD

**Issue by PriyangaRamasamy** [ibm-openbmc/openpower-vpd-parser#297]
Docker CI throws potential memory leak warning created by the variable `l_srcVpdPtr' in the file src/backup_restore.cpp, in method **std::tuple<types::VPDMapVariant, types::VPDMapVariant>
    BackupAndRestore::backupAndRestore()**

Attached the screenshot
<img width="1920" alt="Screenshot 2024-07-16 at 4 21 38 PM (2)" src="https://github.com/user-attachments/assets/f0fe61d4-5a5a-42a3-abe6-c48b135bda87">

**Comment by branupama** [comment]
In the latest code memory leak issue has beed addressed for backup and restore and observed that  there is no memory leak logs when CI runs on latest code.
