### ISSUE TITLE
Don't prime inventory which require CCIN checks

### ISSUE THREAD

**Issue by SunnySrivastava1984** [ibm-openbmc/openpower-vpd-parser#302]
Not all FRU needs to be primed in case the file is not found.
Few inventory paths are to be populated based on CCIN checks hence need not be primed if has tag for CCIN check in JSON.

**Comment by souvik1914581** [comment]
This issue has already been addressed by [commit](https://github.com/souvik1914581/openpower-vpd-parser/commit/b84744b46083be2353d12d7c4c5c1c613992ce3c) and the code is in `P11_Dev` branch [src/worker.cpp in `Worker::primeInventory()`](https://github.com/ibm-openbmc/openpower-vpd-parser/blob/6796854243dde40d71ec65f265650dfd6de2f084/src/worker.cpp#L758)

Closing this issue.
